 version: '2'
 services:

#  api:
#   build: ./api
#   ports:
#    - "9000:9000"
#   expose:
#    - "9000"
#   links:
#    - dynamodb
#    - mongodb

  mongodb:
   ports:
    - "27017:27017"
   expose:
    - "27017"
   image: mongo

  redis:
   ports:
    - "6379:6379"
   expose:
    - "6379"
   image: redis
